/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FieldVisibilityLevel = { 'publicField' : null } |
  { 'premiumOnly' : null };
export interface NewTradeData {
  'key' : string,
  'currentPrice' : string,
  'duration' : string,
  'shares' : string,
  'ratedPerTrade' : string,
  'tradeType' : string,
  'riskPerTrade' : string,
  'contractNotes' : string,
  'exit' : string,
  'entry' : string,
  'position' : string,
  'potential' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete a trade. Admin-only.
   */
  'deleteTrade' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the full visibility config. Admin-only.
   */
  'getFieldVisibilityConfig' : ActorMethod<
    [],
    Array<[string, FieldVisibilityLevel]>
  >,
  /**
   * / Return only the public-facing visibility info (no auth required).
   */
  'getPublicFieldVisibility' : ActorMethod<
    [],
    Array<[string, FieldVisibilityLevel]>
  >,
  /**
   * / Retrieve a single trade, with field-level visibility applied.
   */
  'getTrade' : ActorMethod<[string], [] | [NewTradeData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Returns the role of the calling principal.
   */
  'getUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all trades, with field-level visibility applied per caller role.
   */
  'listTrades' : ActorMethod<[], Array<NewTradeData>>,
  /**
   * / List all principals and their roles. Admin-only.
   */
  'listUsers' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Add or update a trade. Only authenticated users (non-guest) may write.
   */
  'saveTrade' : ActorMethod<[NewTradeData], undefined>,
  /**
   * / Set visibility for a single field. Admin-only.
   */
  'setFieldVisibility' : ActorMethod<[string, FieldVisibilityLevel], undefined>,
  /**
   * / Assign a role to a principal. Admin-only (guard is inside assignRole).
   */
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];