/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FieldVisibilityLevel = IDL.Variant({
  'publicField' : IDL.Null,
  'premiumOnly' : IDL.Null,
});
export const NewTradeData = IDL.Record({
  'key' : IDL.Text,
  'currentPrice' : IDL.Text,
  'duration' : IDL.Text,
  'shares' : IDL.Text,
  'ratedPerTrade' : IDL.Text,
  'tradeType' : IDL.Text,
  'riskPerTrade' : IDL.Text,
  'contractNotes' : IDL.Text,
  'exit' : IDL.Text,
  'entry' : IDL.Text,
  'position' : IDL.Text,
  'potential' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTrade' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFieldVisibilityConfig' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, FieldVisibilityLevel))],
      ['query'],
    ),
  'getPublicFieldVisibility' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, FieldVisibilityLevel))],
      ['query'],
    ),
  'getTrade' : IDL.Func([IDL.Text], [IDL.Opt(NewTradeData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTrades' : IDL.Func([], [IDL.Vec(NewTradeData)], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTrade' : IDL.Func([NewTradeData], [], []),
  'setFieldVisibility' : IDL.Func([IDL.Text, FieldVisibilityLevel], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FieldVisibilityLevel = IDL.Variant({
    'publicField' : IDL.Null,
    'premiumOnly' : IDL.Null,
  });
  const NewTradeData = IDL.Record({
    'key' : IDL.Text,
    'currentPrice' : IDL.Text,
    'duration' : IDL.Text,
    'shares' : IDL.Text,
    'ratedPerTrade' : IDL.Text,
    'tradeType' : IDL.Text,
    'riskPerTrade' : IDL.Text,
    'contractNotes' : IDL.Text,
    'exit' : IDL.Text,
    'entry' : IDL.Text,
    'position' : IDL.Text,
    'potential' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTrade' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFieldVisibilityConfig' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, FieldVisibilityLevel))],
        ['query'],
      ),
    'getPublicFieldVisibility' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, FieldVisibilityLevel))],
        ['query'],
      ),
    'getTrade' : IDL.Func([IDL.Text], [IDL.Opt(NewTradeData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTrades' : IDL.Func([], [IDL.Vec(NewTradeData)], ['query']),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTrade' : IDL.Func([NewTradeData], [], []),
    'setFieldVisibility' : IDL.Func([IDL.Text, FieldVisibilityLevel], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };